import { CompanyHistory } from "../type";

export const COMPANY_HISTORIES: Array<CompanyHistory> = [
  {
    companyName: "Sunday Ins Indonesia",
    timeRange: "June 2023 - Current",
    tackStacks: [
      "aws",
      "nodejs",
      "typescript",
      "nextjs",
      "s3",
      "psql",
      "mongodb",
      "redis",
      "elasticsearch",
      "kafka",
    ],
    isShownProject: false,
    projects: [
      {
        name: "Sunday Direct Retail",
        jobTitle: "Senior Software Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "June 2023 - Current",
        images: [],
      },
    ],
  },
  {
    companyName: "Flash Coffee",
    timeRange: "Sep 2022 - May 2023",
    isShownProject: false,
    tackStacks: [
      "aws",
      "nodejs",
      "lambda",
      "sqs",
      "sns",
      "s3",
      "psql",
      "mongodb",
      "redis",
      "elasticsearch",
      "rabbitmq",
    ],
    projects: [
      {
        name: "Point Of Sales (PoS Squad)",
        jobTitle: "Technical Lead",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "Sep 2022 - May 2023",
        images: [],
      },
      {
        name: "Payment Integration (Pay Squad)",
        jobTitle: "Senior Software Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "Dec 2021 - Sep 2022",
        images: [],
      },
    ],
  },
  {
    companyName: "Female Daily",
    timeRange: "June 2023 - Current",
    isShownProject: false,
    tackStacks: [
      "aws",
      "nodejs",
      "sqs",
      "sns",
      "s3",
      "psql",
      "mongodb",
      "redis",
      "elasticsearch",
      "rabbitmq",
    ],
    projects: [
      {
        name: "Best of Beauty Award",
        jobTitle: "Senior Software Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "June 2023 - Current",
        images: [],
      }
    ],
  },
  {
    companyName: "Inspigo",
    timeRange: "June 2023 - Current",
    isShownProject: false,
    tackStacks: [
      "aws",
      "nodejs",
      "sqs",
      "sns",
      "s3",
      "psql",
      "mongodb",
      "redis",
      "elasticsearch",
      "rabbitmq",
    ],
    projects: [
      {
        name: "Gamification",
        jobTitle: "Senior Backend Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "Jan 2021 - Aug 2021",
        images: [],
      },
      {
        name: "Video on Demand (client req)",
        jobTitle: "Senior Backend Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "Jan 2020 - Nov 2020",
        images: [],
      },
      {
        name: "Elasticsearch Integration",
        jobTitle: "Senior Backend Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "Aug 2019 - Jan 2020",
        images: [],
      },
      {
        name: "In App Purchase",
        jobTitle: "Senior Backend Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "Jan 2019 - Aug 2019",
        images: [],
      },
      {
        name: "Audio Compression",
        jobTitle: "Backend Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "Apr 2019 - June 2019",
        images: [],
      },
      {
        name: "Login Social Media",
        jobTitle: "Backend Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "Dec 2018 - March 2019",
        images: [],
      },
    ],
  },
  {
    companyName: "Sunday Ins Indonesia",
    timeRange: "June 2023 - Current",
    isShownProject: false,
    tackStacks: [
      "aws",
      "nodejs",
      "sqs",
      "sns",
      "s3",
      "psql",
      "mongodb",
      "redis",
      "elasticsearch",
      "rabbitmq",
    ],
    projects: [
      {
        name: "Sunday Direct Retail",
        jobTitle: "Senior Software Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "June 2023 - Current",
        images: [],
      },
      {
        name: "Sunday Direct Retail",
        jobTitle: "Senior Software Engineer",
        desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione corrupti officia porro? Atque nobis perspiciatis illo eveniet excepturi vero aut explicabo alias eaque dolore neque, molestias deleniti ipsum vel suscipit?`,
        timeRange: "June 2023 - Current",
        images: [],
      },
    ],
  },
];
